<?php
/**
 * Fotofolio Landscape Options
 *
 * WARNING! DO NOT EDIT THIS FILE!
 * Editing below this line should NOT be necessary.
 * Change at your own risk.
 *
 * Option keys:
 *  type      string                Elements: text, textarea, radio, checkbox, file, heading, character
 *                                  Section: general, header, footer, styling, typography, slideshow
 *  name      string                Option name (no spacing)
 *  title     string                Text to display
 *  icon      string                Navigation menu icon (only apply to heading type).
 *                                  Available icons: ads, audio, box, calendar, featured, footer, general, header, help, homepage,
 *                                                   images, layout, main, map, media, miscellanious, mobile, navigation,
 *                                                   portfolio, sidebar, slider, styling, tumblog, typography
 *  options   array                 An array, function name or callback which returns an array.
 *                                  Only apply to select and radio.
 *  desc      string    (optional)  Description, HTML allowed
 *  attrs     array     (optional)  HTML element attributes
 *  std       mixed     (optional)  Default value. May a callback which returns a string value
 *  validate  mixed     (optional)  Validation routine should be called before saving
 *  align     string                Applies to radio type. Value may "horizontal" or "vertical", however "horizontal" is omitted
 *                                  if not specified.
 *
 * Functions should not be placed here!
 *
 * @category   Wordspop
 * @package    WPop
 * @copyright  Copyright (c) 2010-2011 Wordspop
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU GPL version 2
 * @version    $Id:$
 */

$wpop_options = array(

    // General
    array(
        'type'      => 'general'
    ),
    array(
        'type'      => 'textarea',
        'title'     => __('Self Introduction', 'fotofolio_landscape'),
        'name'      => 'intro',
        'desc'      => __('Short brief about your self', 'fotofolio_landscape'),
        'std'       => __('I\'m too lazy to write about myself :D', 'fotofolio_landscape'),
        'attrs'     => array('rows' => 5)
    ),
    array(
        'type'      => 'select',
        'title'     => __('Testimonials Category', 'fotofolio_landscape'),
        'name'      => 'testimonial',
        'desc'      => __('A category which will be treated as the testimonials page.', 'fotofolio_landscape'),
        'options'   => 'wpop_categories_options'
    ),

    // Blog section
    array(
        'type'      => 'heading',
        'title'     => __('Blog', 'fotofolio_landscape'),
        'name'      => 'blog',
        'icon'      => 'blog'
    ),
    array(
        'type'      => 'select',
        'title'     => __('Blog Section', 'fotofolio_landscape'),
        'name'      => 'blog',
        'desc'      => __('A category which will be treated as the blog section.', 'fotofolio_landscape'),
        'options'   => 'wpop_categories_options'
    ),
    array(
        'type'      => 'text',
        'title'     => __('Blog Heading', 'fotofolio_landscape'),
        'name'      => 'blog_title',
        'desc'      => __('Heading title for blog section.', 'fotofolio_landscape'),
        'std'       => __('Blog', 'fotofolio_landscape')
    ),

    // Slideshow
    array(
        'type'      => 'slideshow'
    ),
    array(
        'type'      => 'select',
        'title'     => __('Transition Effect', 'fotofolio_landscape'),
        'name'      => 'slide_fx',
        'desc'      => __('Select the transition effect that you like most', 'fotofolio_landscape'),
        'options'   => array(
            'scrollUp'    => __('Scroll Up', 'fotofolio_landscape'),
            'scrollDown'  => __('Scroll Down', 'fotofolio_landscape'),
            'scrollLeft'  => __('Scroll Left', 'fotofolio_landscape'),
            'scrollRight' => __('Scroll Right', 'fotofolio_landscape'),
            'scrollHorz'  => __('Horizontal Scroll', 'fotofolio_landscape'),
            'scrollVert'  => __('Vertical Scroll', 'fotofolio_landscape'),
            'slideX'      => __('Slide X Axis', 'fotofolio_landscape'),
            'slideY'      => __('Slide Y Axis', 'fotofolio_landscape'),
            'shuffle'     => __('Shuffle', 'fotofolio_landscape'),
            'turnUp'      => __('Turn Up', 'fotofolio_landscape'),
            'turnDown'    => __('Turn Down', 'fotofolio_landscape'),
            'turnLeft'    => __('Turn Left', 'fotofolio_landscape'),
            'turnRight'   => __('Turn Right', 'fotofolio_landscape'),
            'zoom'        => __('Zoom', 'fotofolio_landscape'),
            'fade'        => __('Fade', 'fotofolio_landscape'),
            'fadeZoom'    => __('Fade and Zoom', 'fotofolio_landscape'),
            'blindX'      => __('Blind X Axis', 'fotofolio_landscape'),
            'blindY'      => __('Blind Y Axis', 'fotofolio_landscape'),
            'blindZ'      => __('Blind Z Axis', 'fotofolio_landscape'),
            'growX'       => __('Grow X Axis', 'fotofolio_landscape'),
            'growY'       => __('Grow Y Axis', 'fotofolio_landscape'),
            'curtainX'    => __('Curtain X Axis', 'fotofolio_landscape'),
            'curtainY'    => __('Curtain Y Axis', 'fotofolio_landscape'),
            'cover'       => __('Cover', 'fotofolio_landscape'),
            'uncover'     => __('Uncover', 'fotofolio_landscape'),
            'toss'        => __('Toss', 'fotofolio_landscape'),
            'wipe'        => __('Wipe', 'fotofolio_landscape')
        ),
        'std'       => 'fade'
    ),
    array(
        'type'      => 'text',
        'title'     => __('Transition Speed', 'fotofolio_landscape'),
        'name'      => 'slide_speed',
        'desc'      => 'miliseconds',
        'std'       => 1000
    ),
    array(
        'type'      => 'text',
        'title'     => __('Display Duration', 'fotofolio_landscape'),
        'name'      => 'slide_timeout',
        'desc'      => 'miliseconds',
        'std'       => 10000
    ),

    // Fancybox
    array(
        'type'      => 'heading',
        'name'      => 'fancybox',
        'title'     => __('Fancybox', 'fotofolio_landscape'),
        'icon'      => 'popup'
    ),
    array(
        'type'      => 'checkbox',
        'name'      => 'fancybox_autoscale',
        'title'     => __('Auto Scale', 'fotofolio_landscape'),
        'desc'      => __('Auto scaled the popup to fit the viewport', 'fotofolio_landscape'),
        'std'       => 'true'
    ),
    array(
        'type'      => 'checkbox',
        'name'      => 'fancybox_centeronscroll',
        'title'     => __('Always on Center', 'fotofolio_landscape'),
        'desc'      => __('Popup is always centered while scrolling page', 'fotofolio_landscape'),
    ),
    array(
        'type'      => 'checkbox',
        'name'      => 'fancybox_hideoncontentclick',
        'title'     => __('Close on Click', 'fotofolio_landscape'),
        'desc'      => __('Close the popup if clicking the content', 'fotofolio_landscape'),
    ),
    array(
        'type'      => 'checkbox',
        'name'      => 'fancybox_titleshow',
        'title'     => __('Show Title', 'fotofolio_landscape'),
        'desc'      => __('Show the post title on popup box', 'fotofolio_landscape'),
        'std'       => 'true'
    ),
    array(
        'type'      => 'radio',
        'name'      => 'fancybox_titleposition',
        'title'     => __('Title Position', 'fotofolio_landscape'),
        'desc'      => __('The position of title should be placed', 'fotofolio_landscape'),
        'options'   => array('inside' => 'Inside', 'outside' => 'Outside', 'over' => 'Over'),
        'std'       => 'inside'
    ),

    // Styling
    array(
        'type'      => 'styling',
        'excepts'   => array('background_color', 'background_image', 'background_repeat', 'background_position')
    ),
    
    // Typography
    array(
        'type'      => 'typography'
    ),

    // Footer
    array(
        'type'      => 'header'
    ),

    // Footer
    array(
        'type'      => 'footer'
    ),

    // Miscellanious
    array(
        'type'      => 'heading',
        'title'     => __('Miscellanious', 'fotofolio_landscape'),
        'name'      => 'misc',
        'icon'      => 'miscellanious'
    ),
    array(
        'type'      => 'radio',
        'name'      => 'detail_comment',
        'title'     => __('Allow Comment', 'fotofolio_landscape'),
        'options'   => array(
            'yes' => __('Yes, show the comment', 'fotofolio_landscape'),
            'no'  => __('No, don\'t let them comment on my work', 'fotofolio_landscape')
        ),
        'std'       => 'yes',
        'align'     => 'vertical',
        'desc'      => __('Allow visitor to post a comment', 'fotofolio_landscape')
    ),
    array(
        'type'      => 'radio',
        'name'      => 'prevent_rightclick',
        'title'     => __('Prevent Right Click', 'fotofolio_landscape'),
        'options'   => array(
            'yes' => __('Yes', 'fotofolio_landscape'),
            'no' => __('No', 'fotofolio_landscape')
        ),
        'std'       => 'no',
        'desc'      => __('Prevent visitor to right click the document (e.g for saving the stuffs)', 'fotofolio_landscape')
    )

);
